# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mackenzie CPT
email: mcpt.ca@gmail.com
repository: mcpt/mcpt.github.io
description: > # this means to ignore newlines until minipage"baseurl:"
  This is the website for the William Lyon Mackenzie Computer Programming Team.
  Here you can learn about competitive programming.
  We also have lessons appropriate for your high school ICS courses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Mackenzie_CPT
github_username: mcpt

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - ndir/

sass:
  style: compressed

collections:
  cpt-lessons:
    output: true
    permalink: /:collection/:path/
  ics-lessons:
    output: true
    permalink: /:collection/:path/
  cpt-problems:
    output: true
    permalink: /:collection/:path/
  cpt-editorials:
    output: true
    permalink: /:collection/:path/

kramdown:
  math_engine_opts:
    preview: true
