title: Mackenzie Computer Programming Team
email: contact@mcpt.ca
description: Mackenzie Computer Programming Team's Website
markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-admin
input: GFM
syntax_highlighter: rouge
assets:
  compression: true
  source_maps: false
  defaults:
   js: { integrity: true }
  css: { integrity: true } 
  img: { integrity: true }
  plugins:
    img: { optim: {} }
    css: { autoprefixer: {} }